@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
###
@name = hello
GET https://{{host}}/authors HTTP/1.1
###
POST  /registrar HTTP/1.1
Host: {{host}}
Content-Type: {{contentType}}

{
    "nome": "iago",
    "email": "iago@gmail.com",
    "senha": "123456"
}
###
POST /login HTTP/1.1
Host: {{host}}
Content-Type: {{contentType}}

{
    "email":"paulo@teste.com",
    "senha":"teste123456"
}

###
GET /contatos HTTP/1.1
Host: {{host}}
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Niwibm9tZSI6IlBhdWxvIiwiZW1haWwiOiJwYXVsb0B0ZXN0ZS5jb20iLCJpYXQiOjE2MzQxNjg3MzR9.EJ_76zBRymcnTcQruUcvmmoReIV1O_HtlyX_VgxGVqw

